package com.sakura.webservice.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.sakura.webservice.StateServlet;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-03-25T19:13:31.260+08:00
 * Generated source version: 3.2.2
 *
 */
@WebServiceClient(name = "StateServletImplService",
                  wsdlLocation = "http://localhost:8080/WS_Spring/webservice/stateServletForAD?wsdl",
                  targetNamespace = "http://impl.webservice.sakura.com/")
public class StateServletImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webservice.sakura.com/", "StateServletImplService");
    public final static QName StateServletImplPort = new QName("http://impl.webservice.sakura.com/", "StateServletImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/WS_Spring/webservice/stateServletForAD?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StateServletImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/WS_Spring/webservice/stateServletForAD?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StateServletImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StateServletImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StateServletImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public StateServletImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public StateServletImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public StateServletImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns StateServlet
     */
    @WebEndpoint(name = "StateServletImplPort")
    public StateServlet getStateServletImplPort() {
        return super.getPort(StateServletImplPort, StateServlet.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StateServlet
     */
    @WebEndpoint(name = "StateServletImplPort")
    public StateServlet getStateServletImplPort(WebServiceFeature... features) {
        return super.getPort(StateServletImplPort, StateServlet.class, features);
    }

}
