package com.sakura.webservice.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.sakura.webservice.UserLogin;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-03-23T17:33:38.106+08:00
 * Generated source version: 3.2.2
 *
 */
@WebServiceClient(name = "UserLoginImplService",
                  wsdlLocation = "http://localhost:8080/WS_Spring/webservice/UserLogin?wsdl",
                  targetNamespace = "http://impl.webservice.sakura.com/")
public class UserLoginImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webservice.sakura.com/", "UserLoginImplService");
    public final static QName UserLoginImplPort = new QName("http://impl.webservice.sakura.com/", "UserLoginImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/WS_Spring/webservice/UserLogin?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserLoginImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/WS_Spring/webservice/UserLogin?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserLoginImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserLoginImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserLoginImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public UserLoginImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UserLoginImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UserLoginImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns UserLogin
     */
    @WebEndpoint(name = "UserLoginImplPort")
    public UserLogin getUserLoginImplPort() {
        return super.getPort(UserLoginImplPort, UserLogin.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserLogin
     */
    @WebEndpoint(name = "UserLoginImplPort")
    public UserLogin getUserLoginImplPort(WebServiceFeature... features) {
        return super.getPort(UserLoginImplPort, UserLogin.class, features);
    }

}
