package com.sakura.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-03-25T19:13:31.216+08:00
 * Generated source version: 3.2.2
 *
 */
@WebService(targetNamespace = "http://webservice.sakura.com/", name = "StateServlet")
@XmlSeeAlso({ObjectFactory.class})
public interface StateServlet {

    @WebMethod
    @RequestWrapper(localName = "updateState", targetNamespace = "http://webservice.sakura.com/", className = "com.sakura.webservice.UpdateState")
    @ResponseWrapper(localName = "updateStateResponse", targetNamespace = "http://webservice.sakura.com/", className = "com.sakura.webservice.UpdateStateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int updateState(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sakura.webservice.State arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findAllList", targetNamespace = "http://webservice.sakura.com/", className = "com.sakura.webservice.FindAllList")
    @ResponseWrapper(localName = "findAllListResponse", targetNamespace = "http://webservice.sakura.com/", className = "com.sakura.webservice.FindAllListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.sakura.webservice.State> findAllList();

    @WebMethod
    @RequestWrapper(localName = "findStateByName", targetNamespace = "http://webservice.sakura.com/", className = "com.sakura.webservice.FindStateByName")
    @ResponseWrapper(localName = "findStateByNameResponse", targetNamespace = "http://webservice.sakura.com/", className = "com.sakura.webservice.FindStateByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.sakura.webservice.State findStateByName(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findStateByKind", targetNamespace = "http://webservice.sakura.com/", className = "com.sakura.webservice.FindStateByKind")
    @ResponseWrapper(localName = "findStateByKindResponse", targetNamespace = "http://webservice.sakura.com/", className = "com.sakura.webservice.FindStateByKindResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.sakura.webservice.State> findStateByKind(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0
    );

    @WebMethod
    @RequestWrapper(localName = "addState", targetNamespace = "http://webservice.sakura.com/", className = "com.sakura.webservice.AddState")
    @ResponseWrapper(localName = "addStateResponse", targetNamespace = "http://webservice.sakura.com/", className = "com.sakura.webservice.AddStateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int addState(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sakura.webservice.State arg0
    );

    @WebMethod
    @RequestWrapper(localName = "deleteState", targetNamespace = "http://webservice.sakura.com/", className = "com.sakura.webservice.DeleteState")
    @ResponseWrapper(localName = "deleteStateResponse", targetNamespace = "http://webservice.sakura.com/", className = "com.sakura.webservice.DeleteStateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int deleteState(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sakura.webservice.State arg0
    );
}
