package com.sakura.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-03-23T17:33:37.996+08:00
 * Generated source version: 3.2.2
 *
 */
@WebService(targetNamespace = "http://webservice.sakura.com/", name = "UserLogin")
@XmlSeeAlso({ObjectFactory.class})
public interface UserLogin {

    @WebMethod
    @RequestWrapper(localName = "login", targetNamespace = "http://webservice.sakura.com/", className = "com.sakura.webservice.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://webservice.sakura.com/", className = "com.sakura.webservice.LoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.sakura.webservice.User login(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sakura.webservice.User arg0
    );
}
